/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ManagementRouteRouteImport } from './routes/management/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagementUsersRouteImport } from './routes/management/users'
import { Route as ManagementSupportRouteImport } from './routes/management/support'
import { Route as ManagementSuperAdminRouteImport } from './routes/management/super-admin'
import { Route as ManagementSettingsRouteImport } from './routes/management/settings'
import { Route as ManagementLoginRouteImport } from './routes/management/login'
import { Route as ManagementChatRouteImport } from './routes/management/chat'
import { Route as ManagementChangePasswordRouteImport } from './routes/management/change-password'
import { Route as ManagementAdminRouteImport } from './routes/management/admin'
import { Route as ManagementAccessDeniedRouteImport } from './routes/management/access-denied'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedTrustCenterRouteImport } from './routes/_authenticated/trust-center'
import { Route as AuthenticatedTournamentWinnerRouteImport } from './routes/_authenticated/tournament-winner'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedStatusRouteImport } from './routes/_authenticated/status'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedPayoutRouteImport } from './routes/_authenticated/payout'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyPredictionsRouteImport } from './routes/_authenticated/my-predictions'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated/changelog'
import { Route as AuthenticatedBetsRouteImport } from './routes/_authenticated/bets'
import { Route as ManagementAdminIndexRouteImport } from './routes/management/admin.index'
import { Route as AuthenticatedMatchesIndexRouteImport } from './routes/_authenticated/matches.index'
import { Route as ManagementAdminWalletLedgerRouteImport } from './routes/management/admin.wallet-ledger'
import { Route as ManagementAdminWalletAdjustmentsRouteImport } from './routes/management/admin.wallet-adjustments'
import { Route as ManagementAdminUsersRouteImport } from './routes/management/admin.users'
import { Route as ManagementAdminTournamentRouteImport } from './routes/management/admin.tournament'
import { Route as ManagementAdminTokenLedgerRouteImport } from './routes/management/admin.token-ledger'
import { Route as ManagementAdminSupportOpsRouteImport } from './routes/management/admin.support-ops'
import { Route as ManagementAdminStoreRouteImport } from './routes/management/admin.store'
import { Route as ManagementAdminStaffRouteImport } from './routes/management/admin.staff'
import { Route as ManagementAdminSimulationRouteImport } from './routes/management/admin.simulation'
import { Route as ManagementAdminSettlementsRouteImport } from './routes/management/admin.settlements'
import { Route as ManagementAdminSettingsRouteImport } from './routes/management/admin.settings'
import { Route as ManagementAdminRiskSettingsRouteImport } from './routes/management/admin.risk-settings'
import { Route as ManagementAdminReviewRouteImport } from './routes/management/admin.review'
import { Route as ManagementAdminReferredUsersRouteImport } from './routes/management/admin.referred-users'
import { Route as ManagementAdminReferralsRouteImport } from './routes/management/admin.referrals'
import { Route as ManagementAdminReconciliationRouteImport } from './routes/management/admin.reconciliation'
import { Route as ManagementAdminPricingBreakdownRouteImport } from './routes/management/admin.pricing-breakdown'
import { Route as ManagementAdminPredictionsRouteImport } from './routes/management/admin.predictions'
import { Route as ManagementAdminPointsRouteImport } from './routes/management/admin.points'
import { Route as ManagementAdminPayoutsRouteImport } from './routes/management/admin.payouts'
import { Route as ManagementAdminOperationsRouteImport } from './routes/management/admin.operations'
import { Route as ManagementAdminOnboardingRouteImport } from './routes/management/admin.onboarding'
import { Route as ManagementAdminOddsProviderRouteImport } from './routes/management/admin.odds-provider'
import { Route as ManagementAdminOddsHistoryRouteImport } from './routes/management/admin.odds-history'
import { Route as ManagementAdminMatchesRouteImport } from './routes/management/admin.matches'
import { Route as ManagementAdminMatchPoolsRouteImport } from './routes/management/admin.match-pools'
import { Route as ManagementAdminMarketRulesRouteImport } from './routes/management/admin.market-rules'
import { Route as ManagementAdminIncidentsRouteImport } from './routes/management/admin.incidents'
import { Route as ManagementAdminHealthRouteImport } from './routes/management/admin.health'
import { Route as ManagementAdminCorrelatedRiskRouteImport } from './routes/management/admin.correlated-risk'
import { Route as ManagementAdminBankrollRouteImport } from './routes/management/admin.bankroll'
import { Route as ManagementAdminAuditRouteImport } from './routes/management/admin.audit'
import { Route as ManagementAdminAnalyticsRouteImport } from './routes/management/admin.analytics'
import { Route as ManagementAdminAlertsRouteImport } from './routes/management/admin.alerts'
import { Route as AuthenticatedWalletTransactionListRouteImport } from './routes/_authenticated/wallet.transaction-list'
import { Route as AuthenticatedMatchesMatchIdRouteImport } from './routes/_authenticated/matches.$matchId'
import { Route as AuthenticatedFreeBetsPlaceRouteImport } from './routes/_authenticated/free-bets.place'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksSyncFixturesRouteImport } from './routes/api/public/hooks/sync-fixtures'
import { Route as ApiPublicHooksReconciliationRouteImport } from './routes/api/public/hooks/reconciliation'
import { Route as ApiPublicHooksHealthCheckRouteImport } from './routes/api/public/hooks/health-check'
import { Route as ApiPublicHooksApifootballSyncRouteImport } from './routes/api/public/hooks/apifootball-sync'
import { Route as ApiPublicHooksApifootballPrematchRouteImport } from './routes/api/public/hooks/apifootball-prematch'
import { Route as ApiPublicHooksApifootballLiveRouteImport } from './routes/api/public/hooks/apifootball-live'
import { Route as ApiPublicHooksApifootballLineupsRouteImport } from './routes/api/public/hooks/apifootball-lineups'
import { Route as ApiPublicHooksApifootballFulltimeRouteImport } from './routes/api/public/hooks/apifootball-fulltime'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRouteRoute = ManagementRouteRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementUsersRoute = ManagementUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementSupportRoute = ManagementSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementSuperAdminRoute = ManagementSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementSettingsRoute = ManagementSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementLoginRoute = ManagementLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementChatRoute = ManagementChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementChangePasswordRoute =
  ManagementChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => ManagementRouteRoute,
  } as any)
const ManagementAdminRoute = ManagementAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementAccessDeniedRoute = ManagementAccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrustCenterRoute =
  AuthenticatedTrustCenterRouteImport.update({
    id: '/trust-center',
    path: '/trust-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTournamentWinnerRoute =
  AuthenticatedTournamentWinnerRouteImport.update({
    id: '/tournament-winner',
    path: '/tournament-winner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatusRoute = AuthenticatedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayoutRoute = AuthenticatedPayoutRouteImport.update({
  id: '/payout',
  path: '/payout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyPredictionsRoute =
  AuthenticatedMyPredictionsRouteImport.update({
    id: '/my-predictions',
    path: '/my-predictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBetsRoute = AuthenticatedBetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ManagementAdminIndexRoute = ManagementAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const AuthenticatedMatchesIndexRoute =
  AuthenticatedMatchesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMatchesRoute,
  } as any)
const ManagementAdminWalletLedgerRoute =
  ManagementAdminWalletLedgerRouteImport.update({
    id: '/wallet-ledger',
    path: '/wallet-ledger',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminWalletAdjustmentsRoute =
  ManagementAdminWalletAdjustmentsRouteImport.update({
    id: '/wallet-adjustments',
    path: '/wallet-adjustments',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminUsersRoute = ManagementAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const ManagementAdminTournamentRoute =
  ManagementAdminTournamentRouteImport.update({
    id: '/tournament',
    path: '/tournament',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminTokenLedgerRoute =
  ManagementAdminTokenLedgerRouteImport.update({
    id: '/token-ledger',
    path: '/token-ledger',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminSupportOpsRoute =
  ManagementAdminSupportOpsRouteImport.update({
    id: '/support-ops',
    path: '/support-ops',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminStoreRoute = ManagementAdminStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const ManagementAdminStaffRoute = ManagementAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const ManagementAdminSimulationRoute =
  ManagementAdminSimulationRouteImport.update({
    id: '/simulation',
    path: '/simulation',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminSettlementsRoute =
  ManagementAdminSettlementsRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminSettingsRoute = ManagementAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const ManagementAdminRiskSettingsRoute =
  ManagementAdminRiskSettingsRouteImport.update({
    id: '/risk-settings',
    path: '/risk-settings',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminReviewRoute = ManagementAdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const ManagementAdminReferredUsersRoute =
  ManagementAdminReferredUsersRouteImport.update({
    id: '/referred-users',
    path: '/referred-users',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminReferralsRoute =
  ManagementAdminReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminReconciliationRoute =
  ManagementAdminReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminPricingBreakdownRoute =
  ManagementAdminPricingBreakdownRouteImport.update({
    id: '/pricing-breakdown',
    path: '/pricing-breakdown',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminPredictionsRoute =
  ManagementAdminPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminPointsRoute = ManagementAdminPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const ManagementAdminPayoutsRoute = ManagementAdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const ManagementAdminOperationsRoute =
  ManagementAdminOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminOnboardingRoute =
  ManagementAdminOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminOddsProviderRoute =
  ManagementAdminOddsProviderRouteImport.update({
    id: '/odds-provider',
    path: '/odds-provider',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminOddsHistoryRoute =
  ManagementAdminOddsHistoryRouteImport.update({
    id: '/odds-history',
    path: '/odds-history',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminMatchesRoute = ManagementAdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const ManagementAdminMatchPoolsRoute =
  ManagementAdminMatchPoolsRouteImport.update({
    id: '/match-pools',
    path: '/match-pools',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminMarketRulesRoute =
  ManagementAdminMarketRulesRouteImport.update({
    id: '/market-rules',
    path: '/market-rules',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminIncidentsRoute =
  ManagementAdminIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminHealthRoute = ManagementAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const ManagementAdminCorrelatedRiskRoute =
  ManagementAdminCorrelatedRiskRouteImport.update({
    id: '/correlated-risk',
    path: '/correlated-risk',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminBankrollRoute = ManagementAdminBankrollRouteImport.update({
  id: '/bankroll',
  path: '/bankroll',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const ManagementAdminAuditRoute = ManagementAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const ManagementAdminAnalyticsRoute =
  ManagementAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ManagementAdminRoute,
  } as any)
const ManagementAdminAlertsRoute = ManagementAdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ManagementAdminRoute,
} as any)
const AuthenticatedWalletTransactionListRoute =
  AuthenticatedWalletTransactionListRouteImport.update({
    id: '/transaction-list',
    path: '/transaction-list',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedMatchesMatchIdRoute =
  AuthenticatedMatchesMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => AuthenticatedMatchesRoute,
  } as any)
const AuthenticatedFreeBetsPlaceRoute =
  AuthenticatedFreeBetsPlaceRouteImport.update({
    id: '/free-bets/place',
    path: '/free-bets/place',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncFixturesRoute =
  ApiPublicHooksSyncFixturesRouteImport.update({
    id: '/api/public/hooks/sync-fixtures',
    path: '/api/public/hooks/sync-fixtures',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReconciliationRoute =
  ApiPublicHooksReconciliationRouteImport.update({
    id: '/api/public/hooks/reconciliation',
    path: '/api/public/hooks/reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHealthCheckRoute =
  ApiPublicHooksHealthCheckRouteImport.update({
    id: '/api/public/hooks/health-check',
    path: '/api/public/hooks/health-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApifootballSyncRoute =
  ApiPublicHooksApifootballSyncRouteImport.update({
    id: '/api/public/hooks/apifootball-sync',
    path: '/api/public/hooks/apifootball-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApifootballPrematchRoute =
  ApiPublicHooksApifootballPrematchRouteImport.update({
    id: '/api/public/hooks/apifootball-prematch',
    path: '/api/public/hooks/apifootball-prematch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApifootballLiveRoute =
  ApiPublicHooksApifootballLiveRouteImport.update({
    id: '/api/public/hooks/apifootball-live',
    path: '/api/public/hooks/apifootball-live',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApifootballLineupsRoute =
  ApiPublicHooksApifootballLineupsRouteImport.update({
    id: '/api/public/hooks/apifootball-lineups',
    path: '/api/public/hooks/apifootball-lineups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApifootballFulltimeRoute =
  ApiPublicHooksApifootballFulltimeRouteImport.update({
    id: '/api/public/hooks/apifootball-fulltime',
    path: '/api/public/hooks/apifootball-fulltime',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/management': typeof ManagementRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/performance': typeof PerformanceRoute
  '/register': typeof RegisterRoute
  '/bets': typeof AuthenticatedBetsRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/matches': typeof AuthenticatedMatchesRouteWithChildren
  '/my-predictions': typeof AuthenticatedMyPredictionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payout': typeof AuthenticatedPayoutRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/status': typeof AuthenticatedStatusRoute
  '/store': typeof AuthenticatedStoreRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tournament-winner': typeof AuthenticatedTournamentWinnerRoute
  '/trust-center': typeof AuthenticatedTrustCenterRoute
  '/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/management/access-denied': typeof ManagementAccessDeniedRoute
  '/management/admin': typeof ManagementAdminRouteWithChildren
  '/management/change-password': typeof ManagementChangePasswordRoute
  '/management/chat': typeof ManagementChatRoute
  '/management/login': typeof ManagementLoginRoute
  '/management/settings': typeof ManagementSettingsRoute
  '/management/super-admin': typeof ManagementSuperAdminRoute
  '/management/support': typeof ManagementSupportRoute
  '/management/users': typeof ManagementUsersRoute
  '/free-bets/place': typeof AuthenticatedFreeBetsPlaceRoute
  '/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/wallet/transaction-list': typeof AuthenticatedWalletTransactionListRoute
  '/management/admin/alerts': typeof ManagementAdminAlertsRoute
  '/management/admin/analytics': typeof ManagementAdminAnalyticsRoute
  '/management/admin/audit': typeof ManagementAdminAuditRoute
  '/management/admin/bankroll': typeof ManagementAdminBankrollRoute
  '/management/admin/correlated-risk': typeof ManagementAdminCorrelatedRiskRoute
  '/management/admin/health': typeof ManagementAdminHealthRoute
  '/management/admin/incidents': typeof ManagementAdminIncidentsRoute
  '/management/admin/market-rules': typeof ManagementAdminMarketRulesRoute
  '/management/admin/match-pools': typeof ManagementAdminMatchPoolsRoute
  '/management/admin/matches': typeof ManagementAdminMatchesRoute
  '/management/admin/odds-history': typeof ManagementAdminOddsHistoryRoute
  '/management/admin/odds-provider': typeof ManagementAdminOddsProviderRoute
  '/management/admin/onboarding': typeof ManagementAdminOnboardingRoute
  '/management/admin/operations': typeof ManagementAdminOperationsRoute
  '/management/admin/payouts': typeof ManagementAdminPayoutsRoute
  '/management/admin/points': typeof ManagementAdminPointsRoute
  '/management/admin/predictions': typeof ManagementAdminPredictionsRoute
  '/management/admin/pricing-breakdown': typeof ManagementAdminPricingBreakdownRoute
  '/management/admin/reconciliation': typeof ManagementAdminReconciliationRoute
  '/management/admin/referrals': typeof ManagementAdminReferralsRoute
  '/management/admin/referred-users': typeof ManagementAdminReferredUsersRoute
  '/management/admin/review': typeof ManagementAdminReviewRoute
  '/management/admin/risk-settings': typeof ManagementAdminRiskSettingsRoute
  '/management/admin/settings': typeof ManagementAdminSettingsRoute
  '/management/admin/settlements': typeof ManagementAdminSettlementsRoute
  '/management/admin/simulation': typeof ManagementAdminSimulationRoute
  '/management/admin/staff': typeof ManagementAdminStaffRoute
  '/management/admin/store': typeof ManagementAdminStoreRoute
  '/management/admin/support-ops': typeof ManagementAdminSupportOpsRoute
  '/management/admin/token-ledger': typeof ManagementAdminTokenLedgerRoute
  '/management/admin/tournament': typeof ManagementAdminTournamentRoute
  '/management/admin/users': typeof ManagementAdminUsersRoute
  '/management/admin/wallet-adjustments': typeof ManagementAdminWalletAdjustmentsRoute
  '/management/admin/wallet-ledger': typeof ManagementAdminWalletLedgerRoute
  '/matches/': typeof AuthenticatedMatchesIndexRoute
  '/management/admin/': typeof ManagementAdminIndexRoute
  '/api/public/hooks/apifootball-fulltime': typeof ApiPublicHooksApifootballFulltimeRoute
  '/api/public/hooks/apifootball-lineups': typeof ApiPublicHooksApifootballLineupsRoute
  '/api/public/hooks/apifootball-live': typeof ApiPublicHooksApifootballLiveRoute
  '/api/public/hooks/apifootball-prematch': typeof ApiPublicHooksApifootballPrematchRoute
  '/api/public/hooks/apifootball-sync': typeof ApiPublicHooksApifootballSyncRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/api/public/hooks/reconciliation': typeof ApiPublicHooksReconciliationRoute
  '/api/public/hooks/sync-fixtures': typeof ApiPublicHooksSyncFixturesRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/management': typeof ManagementRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/performance': typeof PerformanceRoute
  '/register': typeof RegisterRoute
  '/bets': typeof AuthenticatedBetsRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/my-predictions': typeof AuthenticatedMyPredictionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payout': typeof AuthenticatedPayoutRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/status': typeof AuthenticatedStatusRoute
  '/store': typeof AuthenticatedStoreRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tournament-winner': typeof AuthenticatedTournamentWinnerRoute
  '/trust-center': typeof AuthenticatedTrustCenterRoute
  '/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/management/access-denied': typeof ManagementAccessDeniedRoute
  '/management/change-password': typeof ManagementChangePasswordRoute
  '/management/chat': typeof ManagementChatRoute
  '/management/login': typeof ManagementLoginRoute
  '/management/settings': typeof ManagementSettingsRoute
  '/management/super-admin': typeof ManagementSuperAdminRoute
  '/management/support': typeof ManagementSupportRoute
  '/management/users': typeof ManagementUsersRoute
  '/free-bets/place': typeof AuthenticatedFreeBetsPlaceRoute
  '/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/wallet/transaction-list': typeof AuthenticatedWalletTransactionListRoute
  '/management/admin/alerts': typeof ManagementAdminAlertsRoute
  '/management/admin/analytics': typeof ManagementAdminAnalyticsRoute
  '/management/admin/audit': typeof ManagementAdminAuditRoute
  '/management/admin/bankroll': typeof ManagementAdminBankrollRoute
  '/management/admin/correlated-risk': typeof ManagementAdminCorrelatedRiskRoute
  '/management/admin/health': typeof ManagementAdminHealthRoute
  '/management/admin/incidents': typeof ManagementAdminIncidentsRoute
  '/management/admin/market-rules': typeof ManagementAdminMarketRulesRoute
  '/management/admin/match-pools': typeof ManagementAdminMatchPoolsRoute
  '/management/admin/matches': typeof ManagementAdminMatchesRoute
  '/management/admin/odds-history': typeof ManagementAdminOddsHistoryRoute
  '/management/admin/odds-provider': typeof ManagementAdminOddsProviderRoute
  '/management/admin/onboarding': typeof ManagementAdminOnboardingRoute
  '/management/admin/operations': typeof ManagementAdminOperationsRoute
  '/management/admin/payouts': typeof ManagementAdminPayoutsRoute
  '/management/admin/points': typeof ManagementAdminPointsRoute
  '/management/admin/predictions': typeof ManagementAdminPredictionsRoute
  '/management/admin/pricing-breakdown': typeof ManagementAdminPricingBreakdownRoute
  '/management/admin/reconciliation': typeof ManagementAdminReconciliationRoute
  '/management/admin/referrals': typeof ManagementAdminReferralsRoute
  '/management/admin/referred-users': typeof ManagementAdminReferredUsersRoute
  '/management/admin/review': typeof ManagementAdminReviewRoute
  '/management/admin/risk-settings': typeof ManagementAdminRiskSettingsRoute
  '/management/admin/settings': typeof ManagementAdminSettingsRoute
  '/management/admin/settlements': typeof ManagementAdminSettlementsRoute
  '/management/admin/simulation': typeof ManagementAdminSimulationRoute
  '/management/admin/staff': typeof ManagementAdminStaffRoute
  '/management/admin/store': typeof ManagementAdminStoreRoute
  '/management/admin/support-ops': typeof ManagementAdminSupportOpsRoute
  '/management/admin/token-ledger': typeof ManagementAdminTokenLedgerRoute
  '/management/admin/tournament': typeof ManagementAdminTournamentRoute
  '/management/admin/users': typeof ManagementAdminUsersRoute
  '/management/admin/wallet-adjustments': typeof ManagementAdminWalletAdjustmentsRoute
  '/management/admin/wallet-ledger': typeof ManagementAdminWalletLedgerRoute
  '/matches': typeof AuthenticatedMatchesIndexRoute
  '/management/admin': typeof ManagementAdminIndexRoute
  '/api/public/hooks/apifootball-fulltime': typeof ApiPublicHooksApifootballFulltimeRoute
  '/api/public/hooks/apifootball-lineups': typeof ApiPublicHooksApifootballLineupsRoute
  '/api/public/hooks/apifootball-live': typeof ApiPublicHooksApifootballLiveRoute
  '/api/public/hooks/apifootball-prematch': typeof ApiPublicHooksApifootballPrematchRoute
  '/api/public/hooks/apifootball-sync': typeof ApiPublicHooksApifootballSyncRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/api/public/hooks/reconciliation': typeof ApiPublicHooksReconciliationRoute
  '/api/public/hooks/sync-fixtures': typeof ApiPublicHooksSyncFixturesRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/management': typeof ManagementRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/performance': typeof PerformanceRoute
  '/register': typeof RegisterRoute
  '/_authenticated/bets': typeof AuthenticatedBetsRoute
  '/_authenticated/changelog': typeof AuthenticatedChangelogRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRouteWithChildren
  '/_authenticated/my-predictions': typeof AuthenticatedMyPredictionsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payout': typeof AuthenticatedPayoutRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/status': typeof AuthenticatedStatusRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tournament-winner': typeof AuthenticatedTournamentWinnerRoute
  '/_authenticated/trust-center': typeof AuthenticatedTrustCenterRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/management/access-denied': typeof ManagementAccessDeniedRoute
  '/management/admin': typeof ManagementAdminRouteWithChildren
  '/management/change-password': typeof ManagementChangePasswordRoute
  '/management/chat': typeof ManagementChatRoute
  '/management/login': typeof ManagementLoginRoute
  '/management/settings': typeof ManagementSettingsRoute
  '/management/super-admin': typeof ManagementSuperAdminRoute
  '/management/support': typeof ManagementSupportRoute
  '/management/users': typeof ManagementUsersRoute
  '/_authenticated/free-bets/place': typeof AuthenticatedFreeBetsPlaceRoute
  '/_authenticated/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/_authenticated/wallet/transaction-list': typeof AuthenticatedWalletTransactionListRoute
  '/management/admin/alerts': typeof ManagementAdminAlertsRoute
  '/management/admin/analytics': typeof ManagementAdminAnalyticsRoute
  '/management/admin/audit': typeof ManagementAdminAuditRoute
  '/management/admin/bankroll': typeof ManagementAdminBankrollRoute
  '/management/admin/correlated-risk': typeof ManagementAdminCorrelatedRiskRoute
  '/management/admin/health': typeof ManagementAdminHealthRoute
  '/management/admin/incidents': typeof ManagementAdminIncidentsRoute
  '/management/admin/market-rules': typeof ManagementAdminMarketRulesRoute
  '/management/admin/match-pools': typeof ManagementAdminMatchPoolsRoute
  '/management/admin/matches': typeof ManagementAdminMatchesRoute
  '/management/admin/odds-history': typeof ManagementAdminOddsHistoryRoute
  '/management/admin/odds-provider': typeof ManagementAdminOddsProviderRoute
  '/management/admin/onboarding': typeof ManagementAdminOnboardingRoute
  '/management/admin/operations': typeof ManagementAdminOperationsRoute
  '/management/admin/payouts': typeof ManagementAdminPayoutsRoute
  '/management/admin/points': typeof ManagementAdminPointsRoute
  '/management/admin/predictions': typeof ManagementAdminPredictionsRoute
  '/management/admin/pricing-breakdown': typeof ManagementAdminPricingBreakdownRoute
  '/management/admin/reconciliation': typeof ManagementAdminReconciliationRoute
  '/management/admin/referrals': typeof ManagementAdminReferralsRoute
  '/management/admin/referred-users': typeof ManagementAdminReferredUsersRoute
  '/management/admin/review': typeof ManagementAdminReviewRoute
  '/management/admin/risk-settings': typeof ManagementAdminRiskSettingsRoute
  '/management/admin/settings': typeof ManagementAdminSettingsRoute
  '/management/admin/settlements': typeof ManagementAdminSettlementsRoute
  '/management/admin/simulation': typeof ManagementAdminSimulationRoute
  '/management/admin/staff': typeof ManagementAdminStaffRoute
  '/management/admin/store': typeof ManagementAdminStoreRoute
  '/management/admin/support-ops': typeof ManagementAdminSupportOpsRoute
  '/management/admin/token-ledger': typeof ManagementAdminTokenLedgerRoute
  '/management/admin/tournament': typeof ManagementAdminTournamentRoute
  '/management/admin/users': typeof ManagementAdminUsersRoute
  '/management/admin/wallet-adjustments': typeof ManagementAdminWalletAdjustmentsRoute
  '/management/admin/wallet-ledger': typeof ManagementAdminWalletLedgerRoute
  '/_authenticated/matches/': typeof AuthenticatedMatchesIndexRoute
  '/management/admin/': typeof ManagementAdminIndexRoute
  '/api/public/hooks/apifootball-fulltime': typeof ApiPublicHooksApifootballFulltimeRoute
  '/api/public/hooks/apifootball-lineups': typeof ApiPublicHooksApifootballLineupsRoute
  '/api/public/hooks/apifootball-live': typeof ApiPublicHooksApifootballLiveRoute
  '/api/public/hooks/apifootball-prematch': typeof ApiPublicHooksApifootballPrematchRoute
  '/api/public/hooks/apifootball-sync': typeof ApiPublicHooksApifootballSyncRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/api/public/hooks/reconciliation': typeof ApiPublicHooksReconciliationRoute
  '/api/public/hooks/sync-fixtures': typeof ApiPublicHooksSyncFixturesRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/management'
    | '/about'
    | '/auth'
    | '/brand'
    | '/community'
    | '/faq'
    | '/performance'
    | '/register'
    | '/bets'
    | '/changelog'
    | '/dashboard'
    | '/help'
    | '/matches'
    | '/my-predictions'
    | '/notifications'
    | '/payout'
    | '/referrals'
    | '/settings'
    | '/status'
    | '/store'
    | '/support'
    | '/tournament-winner'
    | '/trust-center'
    | '/wallet'
    | '/management/access-denied'
    | '/management/admin'
    | '/management/change-password'
    | '/management/chat'
    | '/management/login'
    | '/management/settings'
    | '/management/super-admin'
    | '/management/support'
    | '/management/users'
    | '/free-bets/place'
    | '/matches/$matchId'
    | '/wallet/transaction-list'
    | '/management/admin/alerts'
    | '/management/admin/analytics'
    | '/management/admin/audit'
    | '/management/admin/bankroll'
    | '/management/admin/correlated-risk'
    | '/management/admin/health'
    | '/management/admin/incidents'
    | '/management/admin/market-rules'
    | '/management/admin/match-pools'
    | '/management/admin/matches'
    | '/management/admin/odds-history'
    | '/management/admin/odds-provider'
    | '/management/admin/onboarding'
    | '/management/admin/operations'
    | '/management/admin/payouts'
    | '/management/admin/points'
    | '/management/admin/predictions'
    | '/management/admin/pricing-breakdown'
    | '/management/admin/reconciliation'
    | '/management/admin/referrals'
    | '/management/admin/referred-users'
    | '/management/admin/review'
    | '/management/admin/risk-settings'
    | '/management/admin/settings'
    | '/management/admin/settlements'
    | '/management/admin/simulation'
    | '/management/admin/staff'
    | '/management/admin/store'
    | '/management/admin/support-ops'
    | '/management/admin/token-ledger'
    | '/management/admin/tournament'
    | '/management/admin/users'
    | '/management/admin/wallet-adjustments'
    | '/management/admin/wallet-ledger'
    | '/matches/'
    | '/management/admin/'
    | '/api/public/hooks/apifootball-fulltime'
    | '/api/public/hooks/apifootball-lineups'
    | '/api/public/hooks/apifootball-live'
    | '/api/public/hooks/apifootball-prematch'
    | '/api/public/hooks/apifootball-sync'
    | '/api/public/hooks/health-check'
    | '/api/public/hooks/reconciliation'
    | '/api/public/hooks/sync-fixtures'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/management'
    | '/about'
    | '/auth'
    | '/brand'
    | '/community'
    | '/faq'
    | '/performance'
    | '/register'
    | '/bets'
    | '/changelog'
    | '/dashboard'
    | '/help'
    | '/my-predictions'
    | '/notifications'
    | '/payout'
    | '/referrals'
    | '/settings'
    | '/status'
    | '/store'
    | '/support'
    | '/tournament-winner'
    | '/trust-center'
    | '/wallet'
    | '/management/access-denied'
    | '/management/change-password'
    | '/management/chat'
    | '/management/login'
    | '/management/settings'
    | '/management/super-admin'
    | '/management/support'
    | '/management/users'
    | '/free-bets/place'
    | '/matches/$matchId'
    | '/wallet/transaction-list'
    | '/management/admin/alerts'
    | '/management/admin/analytics'
    | '/management/admin/audit'
    | '/management/admin/bankroll'
    | '/management/admin/correlated-risk'
    | '/management/admin/health'
    | '/management/admin/incidents'
    | '/management/admin/market-rules'
    | '/management/admin/match-pools'
    | '/management/admin/matches'
    | '/management/admin/odds-history'
    | '/management/admin/odds-provider'
    | '/management/admin/onboarding'
    | '/management/admin/operations'
    | '/management/admin/payouts'
    | '/management/admin/points'
    | '/management/admin/predictions'
    | '/management/admin/pricing-breakdown'
    | '/management/admin/reconciliation'
    | '/management/admin/referrals'
    | '/management/admin/referred-users'
    | '/management/admin/review'
    | '/management/admin/risk-settings'
    | '/management/admin/settings'
    | '/management/admin/settlements'
    | '/management/admin/simulation'
    | '/management/admin/staff'
    | '/management/admin/store'
    | '/management/admin/support-ops'
    | '/management/admin/token-ledger'
    | '/management/admin/tournament'
    | '/management/admin/users'
    | '/management/admin/wallet-adjustments'
    | '/management/admin/wallet-ledger'
    | '/matches'
    | '/management/admin'
    | '/api/public/hooks/apifootball-fulltime'
    | '/api/public/hooks/apifootball-lineups'
    | '/api/public/hooks/apifootball-live'
    | '/api/public/hooks/apifootball-prematch'
    | '/api/public/hooks/apifootball-sync'
    | '/api/public/hooks/health-check'
    | '/api/public/hooks/reconciliation'
    | '/api/public/hooks/sync-fixtures'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/management'
    | '/about'
    | '/auth'
    | '/brand'
    | '/community'
    | '/faq'
    | '/performance'
    | '/register'
    | '/_authenticated/bets'
    | '/_authenticated/changelog'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/matches'
    | '/_authenticated/my-predictions'
    | '/_authenticated/notifications'
    | '/_authenticated/payout'
    | '/_authenticated/referrals'
    | '/_authenticated/settings'
    | '/_authenticated/status'
    | '/_authenticated/store'
    | '/_authenticated/support'
    | '/_authenticated/tournament-winner'
    | '/_authenticated/trust-center'
    | '/_authenticated/wallet'
    | '/management/access-denied'
    | '/management/admin'
    | '/management/change-password'
    | '/management/chat'
    | '/management/login'
    | '/management/settings'
    | '/management/super-admin'
    | '/management/support'
    | '/management/users'
    | '/_authenticated/free-bets/place'
    | '/_authenticated/matches/$matchId'
    | '/_authenticated/wallet/transaction-list'
    | '/management/admin/alerts'
    | '/management/admin/analytics'
    | '/management/admin/audit'
    | '/management/admin/bankroll'
    | '/management/admin/correlated-risk'
    | '/management/admin/health'
    | '/management/admin/incidents'
    | '/management/admin/market-rules'
    | '/management/admin/match-pools'
    | '/management/admin/matches'
    | '/management/admin/odds-history'
    | '/management/admin/odds-provider'
    | '/management/admin/onboarding'
    | '/management/admin/operations'
    | '/management/admin/payouts'
    | '/management/admin/points'
    | '/management/admin/predictions'
    | '/management/admin/pricing-breakdown'
    | '/management/admin/reconciliation'
    | '/management/admin/referrals'
    | '/management/admin/referred-users'
    | '/management/admin/review'
    | '/management/admin/risk-settings'
    | '/management/admin/settings'
    | '/management/admin/settlements'
    | '/management/admin/simulation'
    | '/management/admin/staff'
    | '/management/admin/store'
    | '/management/admin/support-ops'
    | '/management/admin/token-ledger'
    | '/management/admin/tournament'
    | '/management/admin/users'
    | '/management/admin/wallet-adjustments'
    | '/management/admin/wallet-ledger'
    | '/_authenticated/matches/'
    | '/management/admin/'
    | '/api/public/hooks/apifootball-fulltime'
    | '/api/public/hooks/apifootball-lineups'
    | '/api/public/hooks/apifootball-live'
    | '/api/public/hooks/apifootball-prematch'
    | '/api/public/hooks/apifootball-sync'
    | '/api/public/hooks/health-check'
    | '/api/public/hooks/reconciliation'
    | '/api/public/hooks/sync-fixtures'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ManagementRouteRoute: typeof ManagementRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BrandRoute: typeof BrandRoute
  CommunityRoute: typeof CommunityRoute
  FaqRoute: typeof FaqRoute
  PerformanceRoute: typeof PerformanceRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicHooksApifootballFulltimeRoute: typeof ApiPublicHooksApifootballFulltimeRoute
  ApiPublicHooksApifootballLineupsRoute: typeof ApiPublicHooksApifootballLineupsRoute
  ApiPublicHooksApifootballLiveRoute: typeof ApiPublicHooksApifootballLiveRoute
  ApiPublicHooksApifootballPrematchRoute: typeof ApiPublicHooksApifootballPrematchRoute
  ApiPublicHooksApifootballSyncRoute: typeof ApiPublicHooksApifootballSyncRoute
  ApiPublicHooksHealthCheckRoute: typeof ApiPublicHooksHealthCheckRoute
  ApiPublicHooksReconciliationRoute: typeof ApiPublicHooksReconciliationRoute
  ApiPublicHooksSyncFixturesRoute: typeof ApiPublicHooksSyncFixturesRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/users': {
      id: '/management/users'
      path: '/users'
      fullPath: '/management/users'
      preLoaderRoute: typeof ManagementUsersRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/management/support': {
      id: '/management/support'
      path: '/support'
      fullPath: '/management/support'
      preLoaderRoute: typeof ManagementSupportRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/management/super-admin': {
      id: '/management/super-admin'
      path: '/super-admin'
      fullPath: '/management/super-admin'
      preLoaderRoute: typeof ManagementSuperAdminRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/management/settings': {
      id: '/management/settings'
      path: '/settings'
      fullPath: '/management/settings'
      preLoaderRoute: typeof ManagementSettingsRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/management/login': {
      id: '/management/login'
      path: '/login'
      fullPath: '/management/login'
      preLoaderRoute: typeof ManagementLoginRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/management/chat': {
      id: '/management/chat'
      path: '/chat'
      fullPath: '/management/chat'
      preLoaderRoute: typeof ManagementChatRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/management/change-password': {
      id: '/management/change-password'
      path: '/change-password'
      fullPath: '/management/change-password'
      preLoaderRoute: typeof ManagementChangePasswordRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/management/admin': {
      id: '/management/admin'
      path: '/admin'
      fullPath: '/management/admin'
      preLoaderRoute: typeof ManagementAdminRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/management/access-denied': {
      id: '/management/access-denied'
      path: '/access-denied'
      fullPath: '/management/access-denied'
      preLoaderRoute: typeof ManagementAccessDeniedRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trust-center': {
      id: '/_authenticated/trust-center'
      path: '/trust-center'
      fullPath: '/trust-center'
      preLoaderRoute: typeof AuthenticatedTrustCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tournament-winner': {
      id: '/_authenticated/tournament-winner'
      path: '/tournament-winner'
      fullPath: '/tournament-winner'
      preLoaderRoute: typeof AuthenticatedTournamentWinnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/status': {
      id: '/_authenticated/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthenticatedStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payout': {
      id: '/_authenticated/payout'
      path: '/payout'
      fullPath: '/payout'
      preLoaderRoute: typeof AuthenticatedPayoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-predictions': {
      id: '/_authenticated/my-predictions'
      path: '/my-predictions'
      fullPath: '/my-predictions'
      preLoaderRoute: typeof AuthenticatedMyPredictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bets': {
      id: '/_authenticated/bets'
      path: '/bets'
      fullPath: '/bets'
      preLoaderRoute: typeof AuthenticatedBetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/management/admin/': {
      id: '/management/admin/'
      path: '/'
      fullPath: '/management/admin/'
      preLoaderRoute: typeof ManagementAdminIndexRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/_authenticated/matches/': {
      id: '/_authenticated/matches/'
      path: '/'
      fullPath: '/matches/'
      preLoaderRoute: typeof AuthenticatedMatchesIndexRouteImport
      parentRoute: typeof AuthenticatedMatchesRoute
    }
    '/management/admin/wallet-ledger': {
      id: '/management/admin/wallet-ledger'
      path: '/wallet-ledger'
      fullPath: '/management/admin/wallet-ledger'
      preLoaderRoute: typeof ManagementAdminWalletLedgerRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/wallet-adjustments': {
      id: '/management/admin/wallet-adjustments'
      path: '/wallet-adjustments'
      fullPath: '/management/admin/wallet-adjustments'
      preLoaderRoute: typeof ManagementAdminWalletAdjustmentsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/users': {
      id: '/management/admin/users'
      path: '/users'
      fullPath: '/management/admin/users'
      preLoaderRoute: typeof ManagementAdminUsersRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/tournament': {
      id: '/management/admin/tournament'
      path: '/tournament'
      fullPath: '/management/admin/tournament'
      preLoaderRoute: typeof ManagementAdminTournamentRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/token-ledger': {
      id: '/management/admin/token-ledger'
      path: '/token-ledger'
      fullPath: '/management/admin/token-ledger'
      preLoaderRoute: typeof ManagementAdminTokenLedgerRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/support-ops': {
      id: '/management/admin/support-ops'
      path: '/support-ops'
      fullPath: '/management/admin/support-ops'
      preLoaderRoute: typeof ManagementAdminSupportOpsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/store': {
      id: '/management/admin/store'
      path: '/store'
      fullPath: '/management/admin/store'
      preLoaderRoute: typeof ManagementAdminStoreRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/staff': {
      id: '/management/admin/staff'
      path: '/staff'
      fullPath: '/management/admin/staff'
      preLoaderRoute: typeof ManagementAdminStaffRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/simulation': {
      id: '/management/admin/simulation'
      path: '/simulation'
      fullPath: '/management/admin/simulation'
      preLoaderRoute: typeof ManagementAdminSimulationRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/settlements': {
      id: '/management/admin/settlements'
      path: '/settlements'
      fullPath: '/management/admin/settlements'
      preLoaderRoute: typeof ManagementAdminSettlementsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/settings': {
      id: '/management/admin/settings'
      path: '/settings'
      fullPath: '/management/admin/settings'
      preLoaderRoute: typeof ManagementAdminSettingsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/risk-settings': {
      id: '/management/admin/risk-settings'
      path: '/risk-settings'
      fullPath: '/management/admin/risk-settings'
      preLoaderRoute: typeof ManagementAdminRiskSettingsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/review': {
      id: '/management/admin/review'
      path: '/review'
      fullPath: '/management/admin/review'
      preLoaderRoute: typeof ManagementAdminReviewRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/referred-users': {
      id: '/management/admin/referred-users'
      path: '/referred-users'
      fullPath: '/management/admin/referred-users'
      preLoaderRoute: typeof ManagementAdminReferredUsersRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/referrals': {
      id: '/management/admin/referrals'
      path: '/referrals'
      fullPath: '/management/admin/referrals'
      preLoaderRoute: typeof ManagementAdminReferralsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/reconciliation': {
      id: '/management/admin/reconciliation'
      path: '/reconciliation'
      fullPath: '/management/admin/reconciliation'
      preLoaderRoute: typeof ManagementAdminReconciliationRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/pricing-breakdown': {
      id: '/management/admin/pricing-breakdown'
      path: '/pricing-breakdown'
      fullPath: '/management/admin/pricing-breakdown'
      preLoaderRoute: typeof ManagementAdminPricingBreakdownRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/predictions': {
      id: '/management/admin/predictions'
      path: '/predictions'
      fullPath: '/management/admin/predictions'
      preLoaderRoute: typeof ManagementAdminPredictionsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/points': {
      id: '/management/admin/points'
      path: '/points'
      fullPath: '/management/admin/points'
      preLoaderRoute: typeof ManagementAdminPointsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/payouts': {
      id: '/management/admin/payouts'
      path: '/payouts'
      fullPath: '/management/admin/payouts'
      preLoaderRoute: typeof ManagementAdminPayoutsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/operations': {
      id: '/management/admin/operations'
      path: '/operations'
      fullPath: '/management/admin/operations'
      preLoaderRoute: typeof ManagementAdminOperationsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/onboarding': {
      id: '/management/admin/onboarding'
      path: '/onboarding'
      fullPath: '/management/admin/onboarding'
      preLoaderRoute: typeof ManagementAdminOnboardingRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/odds-provider': {
      id: '/management/admin/odds-provider'
      path: '/odds-provider'
      fullPath: '/management/admin/odds-provider'
      preLoaderRoute: typeof ManagementAdminOddsProviderRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/odds-history': {
      id: '/management/admin/odds-history'
      path: '/odds-history'
      fullPath: '/management/admin/odds-history'
      preLoaderRoute: typeof ManagementAdminOddsHistoryRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/matches': {
      id: '/management/admin/matches'
      path: '/matches'
      fullPath: '/management/admin/matches'
      preLoaderRoute: typeof ManagementAdminMatchesRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/match-pools': {
      id: '/management/admin/match-pools'
      path: '/match-pools'
      fullPath: '/management/admin/match-pools'
      preLoaderRoute: typeof ManagementAdminMatchPoolsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/market-rules': {
      id: '/management/admin/market-rules'
      path: '/market-rules'
      fullPath: '/management/admin/market-rules'
      preLoaderRoute: typeof ManagementAdminMarketRulesRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/incidents': {
      id: '/management/admin/incidents'
      path: '/incidents'
      fullPath: '/management/admin/incidents'
      preLoaderRoute: typeof ManagementAdminIncidentsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/health': {
      id: '/management/admin/health'
      path: '/health'
      fullPath: '/management/admin/health'
      preLoaderRoute: typeof ManagementAdminHealthRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/correlated-risk': {
      id: '/management/admin/correlated-risk'
      path: '/correlated-risk'
      fullPath: '/management/admin/correlated-risk'
      preLoaderRoute: typeof ManagementAdminCorrelatedRiskRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/bankroll': {
      id: '/management/admin/bankroll'
      path: '/bankroll'
      fullPath: '/management/admin/bankroll'
      preLoaderRoute: typeof ManagementAdminBankrollRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/audit': {
      id: '/management/admin/audit'
      path: '/audit'
      fullPath: '/management/admin/audit'
      preLoaderRoute: typeof ManagementAdminAuditRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/analytics': {
      id: '/management/admin/analytics'
      path: '/analytics'
      fullPath: '/management/admin/analytics'
      preLoaderRoute: typeof ManagementAdminAnalyticsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/management/admin/alerts': {
      id: '/management/admin/alerts'
      path: '/alerts'
      fullPath: '/management/admin/alerts'
      preLoaderRoute: typeof ManagementAdminAlertsRouteImport
      parentRoute: typeof ManagementAdminRoute
    }
    '/_authenticated/wallet/transaction-list': {
      id: '/_authenticated/wallet/transaction-list'
      path: '/transaction-list'
      fullPath: '/wallet/transaction-list'
      preLoaderRoute: typeof AuthenticatedWalletTransactionListRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/matches/$matchId': {
      id: '/_authenticated/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdRouteImport
      parentRoute: typeof AuthenticatedMatchesRoute
    }
    '/_authenticated/free-bets/place': {
      id: '/_authenticated/free-bets/place'
      path: '/free-bets/place'
      fullPath: '/free-bets/place'
      preLoaderRoute: typeof AuthenticatedFreeBetsPlaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-fixtures': {
      id: '/api/public/hooks/sync-fixtures'
      path: '/api/public/hooks/sync-fixtures'
      fullPath: '/api/public/hooks/sync-fixtures'
      preLoaderRoute: typeof ApiPublicHooksSyncFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconciliation': {
      id: '/api/public/hooks/reconciliation'
      path: '/api/public/hooks/reconciliation'
      fullPath: '/api/public/hooks/reconciliation'
      preLoaderRoute: typeof ApiPublicHooksReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health-check': {
      id: '/api/public/hooks/health-check'
      path: '/api/public/hooks/health-check'
      fullPath: '/api/public/hooks/health-check'
      preLoaderRoute: typeof ApiPublicHooksHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/apifootball-sync': {
      id: '/api/public/hooks/apifootball-sync'
      path: '/api/public/hooks/apifootball-sync'
      fullPath: '/api/public/hooks/apifootball-sync'
      preLoaderRoute: typeof ApiPublicHooksApifootballSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/apifootball-prematch': {
      id: '/api/public/hooks/apifootball-prematch'
      path: '/api/public/hooks/apifootball-prematch'
      fullPath: '/api/public/hooks/apifootball-prematch'
      preLoaderRoute: typeof ApiPublicHooksApifootballPrematchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/apifootball-live': {
      id: '/api/public/hooks/apifootball-live'
      path: '/api/public/hooks/apifootball-live'
      fullPath: '/api/public/hooks/apifootball-live'
      preLoaderRoute: typeof ApiPublicHooksApifootballLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/apifootball-lineups': {
      id: '/api/public/hooks/apifootball-lineups'
      path: '/api/public/hooks/apifootball-lineups'
      fullPath: '/api/public/hooks/apifootball-lineups'
      preLoaderRoute: typeof ApiPublicHooksApifootballLineupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/apifootball-fulltime': {
      id: '/api/public/hooks/apifootball-fulltime'
      path: '/api/public/hooks/apifootball-fulltime'
      fullPath: '/api/public/hooks/apifootball-fulltime'
      preLoaderRoute: typeof ApiPublicHooksApifootballFulltimeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMatchesRouteChildren {
  AuthenticatedMatchesMatchIdRoute: typeof AuthenticatedMatchesMatchIdRoute
  AuthenticatedMatchesIndexRoute: typeof AuthenticatedMatchesIndexRoute
}

const AuthenticatedMatchesRouteChildren: AuthenticatedMatchesRouteChildren = {
  AuthenticatedMatchesMatchIdRoute: AuthenticatedMatchesMatchIdRoute,
  AuthenticatedMatchesIndexRoute: AuthenticatedMatchesIndexRoute,
}

const AuthenticatedMatchesRouteWithChildren =
  AuthenticatedMatchesRoute._addFileChildren(AuthenticatedMatchesRouteChildren)

interface AuthenticatedWalletRouteChildren {
  AuthenticatedWalletTransactionListRoute: typeof AuthenticatedWalletTransactionListRoute
}

const AuthenticatedWalletRouteChildren: AuthenticatedWalletRouteChildren = {
  AuthenticatedWalletTransactionListRoute:
    AuthenticatedWalletTransactionListRoute,
}

const AuthenticatedWalletRouteWithChildren =
  AuthenticatedWalletRoute._addFileChildren(AuthenticatedWalletRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBetsRoute: typeof AuthenticatedBetsRoute
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRouteWithChildren
  AuthenticatedMyPredictionsRoute: typeof AuthenticatedMyPredictionsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPayoutRoute: typeof AuthenticatedPayoutRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatusRoute: typeof AuthenticatedStatusRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTournamentWinnerRoute: typeof AuthenticatedTournamentWinnerRoute
  AuthenticatedTrustCenterRoute: typeof AuthenticatedTrustCenterRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRouteWithChildren
  AuthenticatedFreeBetsPlaceRoute: typeof AuthenticatedFreeBetsPlaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBetsRoute: AuthenticatedBetsRoute,
  AuthenticatedChangelogRoute: AuthenticatedChangelogRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRouteWithChildren,
  AuthenticatedMyPredictionsRoute: AuthenticatedMyPredictionsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPayoutRoute: AuthenticatedPayoutRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatusRoute: AuthenticatedStatusRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTournamentWinnerRoute: AuthenticatedTournamentWinnerRoute,
  AuthenticatedTrustCenterRoute: AuthenticatedTrustCenterRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRouteWithChildren,
  AuthenticatedFreeBetsPlaceRoute: AuthenticatedFreeBetsPlaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ManagementAdminRouteChildren {
  ManagementAdminAlertsRoute: typeof ManagementAdminAlertsRoute
  ManagementAdminAnalyticsRoute: typeof ManagementAdminAnalyticsRoute
  ManagementAdminAuditRoute: typeof ManagementAdminAuditRoute
  ManagementAdminBankrollRoute: typeof ManagementAdminBankrollRoute
  ManagementAdminCorrelatedRiskRoute: typeof ManagementAdminCorrelatedRiskRoute
  ManagementAdminHealthRoute: typeof ManagementAdminHealthRoute
  ManagementAdminIncidentsRoute: typeof ManagementAdminIncidentsRoute
  ManagementAdminMarketRulesRoute: typeof ManagementAdminMarketRulesRoute
  ManagementAdminMatchPoolsRoute: typeof ManagementAdminMatchPoolsRoute
  ManagementAdminMatchesRoute: typeof ManagementAdminMatchesRoute
  ManagementAdminOddsHistoryRoute: typeof ManagementAdminOddsHistoryRoute
  ManagementAdminOddsProviderRoute: typeof ManagementAdminOddsProviderRoute
  ManagementAdminOnboardingRoute: typeof ManagementAdminOnboardingRoute
  ManagementAdminOperationsRoute: typeof ManagementAdminOperationsRoute
  ManagementAdminPayoutsRoute: typeof ManagementAdminPayoutsRoute
  ManagementAdminPointsRoute: typeof ManagementAdminPointsRoute
  ManagementAdminPredictionsRoute: typeof ManagementAdminPredictionsRoute
  ManagementAdminPricingBreakdownRoute: typeof ManagementAdminPricingBreakdownRoute
  ManagementAdminReconciliationRoute: typeof ManagementAdminReconciliationRoute
  ManagementAdminReferralsRoute: typeof ManagementAdminReferralsRoute
  ManagementAdminReferredUsersRoute: typeof ManagementAdminReferredUsersRoute
  ManagementAdminReviewRoute: typeof ManagementAdminReviewRoute
  ManagementAdminRiskSettingsRoute: typeof ManagementAdminRiskSettingsRoute
  ManagementAdminSettingsRoute: typeof ManagementAdminSettingsRoute
  ManagementAdminSettlementsRoute: typeof ManagementAdminSettlementsRoute
  ManagementAdminSimulationRoute: typeof ManagementAdminSimulationRoute
  ManagementAdminStaffRoute: typeof ManagementAdminStaffRoute
  ManagementAdminStoreRoute: typeof ManagementAdminStoreRoute
  ManagementAdminSupportOpsRoute: typeof ManagementAdminSupportOpsRoute
  ManagementAdminTokenLedgerRoute: typeof ManagementAdminTokenLedgerRoute
  ManagementAdminTournamentRoute: typeof ManagementAdminTournamentRoute
  ManagementAdminUsersRoute: typeof ManagementAdminUsersRoute
  ManagementAdminWalletAdjustmentsRoute: typeof ManagementAdminWalletAdjustmentsRoute
  ManagementAdminWalletLedgerRoute: typeof ManagementAdminWalletLedgerRoute
  ManagementAdminIndexRoute: typeof ManagementAdminIndexRoute
}

const ManagementAdminRouteChildren: ManagementAdminRouteChildren = {
  ManagementAdminAlertsRoute: ManagementAdminAlertsRoute,
  ManagementAdminAnalyticsRoute: ManagementAdminAnalyticsRoute,
  ManagementAdminAuditRoute: ManagementAdminAuditRoute,
  ManagementAdminBankrollRoute: ManagementAdminBankrollRoute,
  ManagementAdminCorrelatedRiskRoute: ManagementAdminCorrelatedRiskRoute,
  ManagementAdminHealthRoute: ManagementAdminHealthRoute,
  ManagementAdminIncidentsRoute: ManagementAdminIncidentsRoute,
  ManagementAdminMarketRulesRoute: ManagementAdminMarketRulesRoute,
  ManagementAdminMatchPoolsRoute: ManagementAdminMatchPoolsRoute,
  ManagementAdminMatchesRoute: ManagementAdminMatchesRoute,
  ManagementAdminOddsHistoryRoute: ManagementAdminOddsHistoryRoute,
  ManagementAdminOddsProviderRoute: ManagementAdminOddsProviderRoute,
  ManagementAdminOnboardingRoute: ManagementAdminOnboardingRoute,
  ManagementAdminOperationsRoute: ManagementAdminOperationsRoute,
  ManagementAdminPayoutsRoute: ManagementAdminPayoutsRoute,
  ManagementAdminPointsRoute: ManagementAdminPointsRoute,
  ManagementAdminPredictionsRoute: ManagementAdminPredictionsRoute,
  ManagementAdminPricingBreakdownRoute: ManagementAdminPricingBreakdownRoute,
  ManagementAdminReconciliationRoute: ManagementAdminReconciliationRoute,
  ManagementAdminReferralsRoute: ManagementAdminReferralsRoute,
  ManagementAdminReferredUsersRoute: ManagementAdminReferredUsersRoute,
  ManagementAdminReviewRoute: ManagementAdminReviewRoute,
  ManagementAdminRiskSettingsRoute: ManagementAdminRiskSettingsRoute,
  ManagementAdminSettingsRoute: ManagementAdminSettingsRoute,
  ManagementAdminSettlementsRoute: ManagementAdminSettlementsRoute,
  ManagementAdminSimulationRoute: ManagementAdminSimulationRoute,
  ManagementAdminStaffRoute: ManagementAdminStaffRoute,
  ManagementAdminStoreRoute: ManagementAdminStoreRoute,
  ManagementAdminSupportOpsRoute: ManagementAdminSupportOpsRoute,
  ManagementAdminTokenLedgerRoute: ManagementAdminTokenLedgerRoute,
  ManagementAdminTournamentRoute: ManagementAdminTournamentRoute,
  ManagementAdminUsersRoute: ManagementAdminUsersRoute,
  ManagementAdminWalletAdjustmentsRoute: ManagementAdminWalletAdjustmentsRoute,
  ManagementAdminWalletLedgerRoute: ManagementAdminWalletLedgerRoute,
  ManagementAdminIndexRoute: ManagementAdminIndexRoute,
}

const ManagementAdminRouteWithChildren = ManagementAdminRoute._addFileChildren(
  ManagementAdminRouteChildren,
)

interface ManagementRouteRouteChildren {
  ManagementAccessDeniedRoute: typeof ManagementAccessDeniedRoute
  ManagementAdminRoute: typeof ManagementAdminRouteWithChildren
  ManagementChangePasswordRoute: typeof ManagementChangePasswordRoute
  ManagementChatRoute: typeof ManagementChatRoute
  ManagementLoginRoute: typeof ManagementLoginRoute
  ManagementSettingsRoute: typeof ManagementSettingsRoute
  ManagementSuperAdminRoute: typeof ManagementSuperAdminRoute
  ManagementSupportRoute: typeof ManagementSupportRoute
  ManagementUsersRoute: typeof ManagementUsersRoute
}

const ManagementRouteRouteChildren: ManagementRouteRouteChildren = {
  ManagementAccessDeniedRoute: ManagementAccessDeniedRoute,
  ManagementAdminRoute: ManagementAdminRouteWithChildren,
  ManagementChangePasswordRoute: ManagementChangePasswordRoute,
  ManagementChatRoute: ManagementChatRoute,
  ManagementLoginRoute: ManagementLoginRoute,
  ManagementSettingsRoute: ManagementSettingsRoute,
  ManagementSuperAdminRoute: ManagementSuperAdminRoute,
  ManagementSupportRoute: ManagementSupportRoute,
  ManagementUsersRoute: ManagementUsersRoute,
}

const ManagementRouteRouteWithChildren = ManagementRouteRoute._addFileChildren(
  ManagementRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ManagementRouteRoute: ManagementRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BrandRoute: BrandRoute,
  CommunityRoute: CommunityRoute,
  FaqRoute: FaqRoute,
  PerformanceRoute: PerformanceRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicHooksApifootballFulltimeRoute:
    ApiPublicHooksApifootballFulltimeRoute,
  ApiPublicHooksApifootballLineupsRoute: ApiPublicHooksApifootballLineupsRoute,
  ApiPublicHooksApifootballLiveRoute: ApiPublicHooksApifootballLiveRoute,
  ApiPublicHooksApifootballPrematchRoute:
    ApiPublicHooksApifootballPrematchRoute,
  ApiPublicHooksApifootballSyncRoute: ApiPublicHooksApifootballSyncRoute,
  ApiPublicHooksHealthCheckRoute: ApiPublicHooksHealthCheckRoute,
  ApiPublicHooksReconciliationRoute: ApiPublicHooksReconciliationRoute,
  ApiPublicHooksSyncFixturesRoute: ApiPublicHooksSyncFixturesRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
